=head1 NAME

Nginx::Runner - run nginx proxy server

=head1 SYNOPSIS

    use Nginx::Runner;

    my $nginx = Nginx::Runner->new;

    $nginx->proxy("127.0.0.1:8080" => "127.0.0.1:3000")->run;

    $SIG{INT} = sub {$nginx->stop};
    sleep;

=head1 COPYRIGHT AND LICENSE

Copyright (C) 2012, Sergey Zasenko.

This program is free software, you can redistribute it and/or modify it under
the same terms as Perl 5.14.

=head1 SEE ALSO

    L<http://nginx.org>

